name: SonarQube Analysis - SpringTC

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sonar:
    name: CI + SonarQube   # 👈 THIS IS THE KEY LINE
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build & Sonar Scan
        run: mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
